# DIR_MINIMALGRAPHICS := libs/minimalgraphics
# DIR_OBJ := build
# FLAGS_C_COMMON :=

# outputs:
# OBJECTS_MINIMALGRAPHICS - added to OBJECTS_TARGET

# $(info Variables: $(.VARIABLES))

ifeq ($(DIR_MINIMALGRAPHICS),)
$(error DIR_MINIMALGRAPHICS is not set)
endif
ifeq ($(FLAGS_C_MINIMALGRAPHICS_CONFIG),)
$(error FLAGS_C_MINIMALGRAPHICS_CONFIG is not set)
endif
ifeq ($(OBJECTS_TARGET),)
$(warning OBJECTS_TARGET is not set)
endif

DIRS_INCLUDE_MINIMALGRAPHICS := $(DIR_MINIMALGRAPHICS)

SOURCES_C_MINIMALGRAPHICS := 
SOURCES_C_MINIMALGRAPHICS += $(DIR_MINIMALGRAPHICS)/mgl.c
SOURCES_C_MINIMALGRAPHICS += $(DIR_MINIMALGRAPHICS)/5monotxt.c
SOURCES_C_MINIMALGRAPHICS += $(DIR_MINIMALGRAPHICS)/5x7mod.c
OBJECTS_MINIMALGRAPHICS := $(addprefix $(DIR_OBJ)/, $(SOURCES_C_MINIMALGRAPHICS:.c=.o))
OBJECTS_TARGET += $(OBJECTS_MINIMALGRAPHICS)
DIR_OBJ_MINIMALGRAPHICS := $(DIR_OBJ)/$(DIR_MINIMALGRAPHICS)

FLAGS_C_MINIMALGRAPHICS := $(FLAGS_C_COMMON)
FLAGS_C_MINIMALGRAPHICS += $(addprefix -I,$(DIRS_INCLUDE_MINIMALGRAPHICS))
FLAGS_C_MINIMALGRAPHICS += -std=c11
FLAGS_C_MINIMALGRAPHICS += -MMD -MP
FLAGS_C_MINIMALGRAPHICS += -Wall -Wextra -Wpedantic
FLAGS_C_MINIMALGRAPHICS += -Wdouble-promotion
FLAGS_C_MINIMALGRAPHICS += $(FLAGS_C_MINIMALGRAPHICS_CONFIG)

$(DIR_OBJ_MINIMALGRAPHICS):
	mkdir -p $@

$(DIR_OBJ_MINIMALGRAPHICS)/%.o: $(DIR_MINIMALGRAPHICS)/%.c | $(DIR_OBJ_MINIMALGRAPHICS)
	@echo "minimalgraphics C> $(notdir $<)"
	@$(CC) -c $(FLAGS_C_MINIMALGRAPHICS) $< -o $@

$(OBJECTS_MINIMALGRAPHICS): $(DIR_MINIMALGRAPHICS)/make.mk

-include $(wildcard $(DIR_OBJ_MINIMALGRAPHICS)/*.d)

# -include $(foreach odir, $(DIRS_OBJS_TARGET), $(wildcard $(odir)/*.d))
